# golangci-lint configuration for Kanary
# See https://golangci-lint.run/usage/configuration/
run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - errcheck
    - errorlint
    - goconst
    - gofmt
    - goimports
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  revive:
    rules:
      - name: exported
      - name: package-comments
      - name: var-naming
      - name: context-as-argument
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unreachable-code
  errorlint:
    errorf: true

issues:
  exclude-dirs:
    - bin
    - config
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unparam
