# ---------------------------------------------------------------------------
# Kanary Operator — Makefile
# ---------------------------------------------------------------------------
# Targets follow the Kubebuilder v4 conventions so that `make <tab>` feels
# familiar to anyone coming from the Operator ecosystem.

SHELL := bash
.ONESHELL:
.DEFAULT_GOAL := help

# -- Versioning --------------------------------------------------------------
VERSION       ?= 0.1.0-dev
IMG_REPO      ?= ghcr.io/adrianbp/kanary
IMG_TAG       ?= $(VERSION)
IMG           ?= $(IMG_REPO):$(IMG_TAG)

# -- Tooling -----------------------------------------------------------------
LOCALBIN      := $(shell pwd)/bin
CONTROLLER_GEN := $(LOCALBIN)/controller-gen
GOLANGCI_LINT := $(LOCALBIN)/golangci-lint
ENVTEST       := $(LOCALBIN)/setup-envtest
GOSEC         := $(LOCALBIN)/gosec
KUBECTL       ?= kubectl

CONTROLLER_TOOLS_VERSION ?= v0.17.3
GOLANGCI_LINT_VERSION    ?= v1.64.8
ENVTEST_K8S_VERSION      ?= 1.31.0
GOSEC_VERSION            ?= v2.22.5

# -- Build metadata ----------------------------------------------------------
LDFLAGS := -s -w \
           -X 'main.buildVersion=$(VERSION)'

# ---------------------------------------------------------------------------
# Help
# ---------------------------------------------------------------------------
.PHONY: help
help: ## Show this help
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n\nTargets:\n"} /^[a-zA-Z0-9_-]+:.*?##/ { printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2 }' $(MAKEFILE_LIST)

# ---------------------------------------------------------------------------
# Code generation & manifests
# ---------------------------------------------------------------------------
.PHONY: manifests
manifests: controller-gen ## Generate CRDs and RBAC manifests (config/)
	$(CONTROLLER_GEN) rbac:roleName=kanary-manager-role \
	  crd:allowDangerousTypes=true webhook paths="./..." \
	  output:crd:artifacts:config=config/crd/bases \
	  output:rbac:artifacts:config=config/rbac \
	  output:webhook:artifacts:config=config/webhook

.PHONY: generate
generate: controller-gen ## Regenerate zz_generated.deepcopy.go
	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./..."

# ---------------------------------------------------------------------------
# Build, run & container
# ---------------------------------------------------------------------------
.PHONY: fmt
fmt: ## gofmt (goimports if available)
	gofmt -s -w ./cmd ./api ./internal

.PHONY: vet
vet: ## go vet
	go vet ./...

.PHONY: lint
lint: golangci-lint ## Run golangci-lint
	$(GOLANGCI_LINT) run ./...

.PHONY: gosec
gosec: $(LOCALBIN) ## Run gosec static security scanner
	test -s $(GOSEC) && $(GOSEC) -version | grep -q $(GOSEC_VERSION) || \
	  GOBIN=$(LOCALBIN) go install github.com/securego/gosec/v2/cmd/gosec@$(GOSEC_VERSION)
	$(GOSEC) ./...

.PHONY: build
build: fmt vet ## Build the manager binary
	CGO_ENABLED=0 go build -ldflags="$(LDFLAGS)" -trimpath -o bin/manager ./cmd/manager

.PHONY: run
run: manifests ## Run the controller locally against the current kube context
	go run ./cmd/manager --metrics-bind-address=:8080

.PHONY: docker-build
docker-build: ## Build the container image
	docker build -t $(IMG) .

.PHONY: docker-push
docker-push: ## Push the container image
	docker push $(IMG)

# ---------------------------------------------------------------------------
# Testing
# ---------------------------------------------------------------------------
.PHONY: test
test: fmt vet envtest ## Run unit & envtest suites with race & coverage
	KUBEBUILDER_ASSETS="$$($(ENVTEST) use $(ENVTEST_K8S_VERSION) -p path)" \
	  go test -race -covermode=atomic -coverprofile=cover.out ./...

.PHONY: cover
cover: test ## Show coverage in the browser
	go tool cover -html=cover.out

# ---------------------------------------------------------------------------
# Deploy (kustomize-based, generated by `kubebuilder init`)
# ---------------------------------------------------------------------------
.PHONY: install
install: manifests ## Install CRDs into the current cluster
	$(KUBECTL) apply -f config/crd/bases/

.PHONY: uninstall
uninstall: ## Remove CRDs from the current cluster
	$(KUBECTL) delete -f config/crd/bases/ --ignore-not-found

# ---------------------------------------------------------------------------
# Local tooling bootstrap
# ---------------------------------------------------------------------------
$(LOCALBIN):
	mkdir -p $(LOCALBIN)

.PHONY: controller-gen
controller-gen: $(LOCALBIN)
	test -s $(CONTROLLER_GEN) && $(CONTROLLER_GEN) --version | grep -q $(CONTROLLER_TOOLS_VERSION) || \
	  GOBIN=$(LOCALBIN) go install sigs.k8s.io/controller-tools/cmd/controller-gen@$(CONTROLLER_TOOLS_VERSION)

.PHONY: golangci-lint
golangci-lint: $(LOCALBIN)
	test -s $(GOLANGCI_LINT) && $(GOLANGCI_LINT) --version | grep -q $(GOLANGCI_LINT_VERSION) || \
	  GOBIN=$(LOCALBIN) go install github.com/golangci/golangci-lint/cmd/golangci-lint@$(GOLANGCI_LINT_VERSION)

.PHONY: envtest
envtest: $(LOCALBIN)
	test -s $(ENVTEST) || \
	  GOBIN=$(LOCALBIN) go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
