{{- if .Values.observability.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kanary.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kanary.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kanary.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      interval: {{ .Values.observability.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.observability.serviceMonitor.scrapeTimeout }}
      path: /metrics
      honorLabels: true
{{- end }}
