apiVersion: v1
kind: Service
metadata:
  name: {{ include "kanary.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kanary.labels" . | nindent 4 }}
spec:
  ports:
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "kanary.selectorLabels" . | nindent 4 }}
