//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.
// This file is checked in so that the package compiles before `make generate`
// has been run. Regenerate after every type change with:
//
//	make generate

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out.
func (in *AnalysisConfig) DeepCopyInto(out *AnalysisConfig) {
	*out = *in
	out.Provider = in.Provider
	if in.Provider.SecretRef != nil {
		in, out := &in.Provider.SecretRef, &out.Provider.SecretRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]MetricCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new AnalysisConfig.
func (in *AnalysisConfig) DeepCopy() *AnalysisConfig {
	if in == nil {
		return nil
	}
	out := new(AnalysisConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for AnalysisReport.
func (in *AnalysisReport) DeepCopyInto(out *AnalysisReport) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]AnalysisResult, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy for AnalysisReport.
func (in *AnalysisReport) DeepCopy() *AnalysisReport {
	if in == nil {
		return nil
	}
	out := new(AnalysisReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for AnalysisResult.
func (in *AnalysisResult) DeepCopyInto(out *AnalysisResult) { *out = *in }

// DeepCopy for AnalysisResult.
func (in *AnalysisResult) DeepCopy() *AnalysisResult {
	if in == nil {
		return nil
	}
	out := new(AnalysisResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for Canary.
func (in *Canary) DeepCopyInto(out *Canary) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy for Canary.
func (in *Canary) DeepCopy() *Canary {
	if in == nil {
		return nil
	}
	out := new(Canary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a generic runtime.Object copy.
func (in *Canary) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for CanaryList.
func (in *CanaryList) DeepCopyInto(out *CanaryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Canary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy for CanaryList.
func (in *CanaryList) DeepCopy() *CanaryList {
	if in == nil {
		return nil
	}
	out := new(CanaryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a generic runtime.Object copy.
func (in *CanaryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for CanarySpec.
func (in *CanarySpec) DeepCopyInto(out *CanarySpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	out.Service = in.Service
	in.TrafficProvider.DeepCopyInto(&out.TrafficProvider)
	in.Strategy.DeepCopyInto(&out.Strategy)
	in.Analysis.DeepCopyInto(&out.Analysis)
}

// DeepCopy for CanarySpec.
func (in *CanarySpec) DeepCopy() *CanarySpec {
	if in == nil {
		return nil
	}
	out := new(CanarySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for CanaryStatus.
func (in *CanaryStatus) DeepCopyInto(out *CanaryStatus) {
	*out = *in
	if in.LastAnalysis != nil {
		in, out := &in.LastAnalysis, &out.LastAnalysis
		*out = new(AnalysisReport)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy for CanaryStatus.
func (in *CanaryStatus) DeepCopy() *CanaryStatus {
	if in == nil {
		return nil
	}
	out := new(CanaryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for LocalObjectReference.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) { *out = *in }

// DeepCopy for LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for MetricCheck.
func (in *MetricCheck) DeepCopyInto(out *MetricCheck) {
	*out = *in
	in.ThresholdRange.DeepCopyInto(&out.ThresholdRange)
}

// DeepCopy for MetricCheck.
func (in *MetricCheck) DeepCopy() *MetricCheck {
	if in == nil {
		return nil
	}
	out := new(MetricCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for MetricProviderConfig.
func (in *MetricProviderConfig) DeepCopyInto(out *MetricProviderConfig) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy for MetricProviderConfig.
func (in *MetricProviderConfig) DeepCopy() *MetricProviderConfig {
	if in == nil {
		return nil
	}
	out := new(MetricProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for ServiceSpec.
func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) { *out = *in }

// DeepCopy for ServiceSpec.
func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for Step.
func (in *Step) DeepCopyInto(out *Step) { *out = *in }

// DeepCopy for Step.
func (in *Step) DeepCopy() *Step {
	if in == nil {
		return nil
	}
	out := new(Step)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for Strategy.
func (in *Strategy) DeepCopyInto(out *Strategy) {
	*out = *in
	out.StepInterval = in.StepInterval
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]Step, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy for Strategy.
func (in *Strategy) DeepCopy() *Strategy {
	if in == nil {
		return nil
	}
	out := new(Strategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for TargetRef.
func (in *TargetRef) DeepCopyInto(out *TargetRef) { *out = *in }

// DeepCopy for TargetRef.
func (in *TargetRef) DeepCopy() *TargetRef {
	if in == nil {
		return nil
	}
	out := new(TargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for ThresholdRange.
func (in *ThresholdRange) DeepCopyInto(out *ThresholdRange) {
	*out = *in
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(float64)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy for ThresholdRange.
func (in *ThresholdRange) DeepCopy() *ThresholdRange {
	if in == nil {
		return nil
	}
	out := new(ThresholdRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for TrafficProvider.
func (in *TrafficProvider) DeepCopyInto(out *TrafficProvider) {
	*out = *in
	if in.IngressRef != nil {
		in, out := &in.IngressRef, &out.IngressRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.RouteRef != nil {
		in, out := &in.RouteRef, &out.RouteRef
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy for TrafficProvider.
func (in *TrafficProvider) DeepCopy() *TrafficProvider {
	if in == nil {
		return nil
	}
	out := new(TrafficProvider)
	in.DeepCopyInto(out)
	return out
}
